#!/usr/bin/env node

PORT = process.env.PORT || 8080

const http = require('http')

http.get(`http://127.0.0.1:${PORT}/health`, res => {
  const { statusCode } = res;
  res.on('data', chunk => {
    console.log('body:', chunk)
  })

  console.log('statusCode:', statusCode)

  if (statusCode !== 200) {
    process.exit(1)
  }
}).on('error', (e) => {
  console.error(`error: ${e.message}`)
  process.exit(1)
})
